export interface ParameterDef {
  id: string
  name: string
  category: 'pre-filter' | 'return' | 'risk' | 'risk-adjusted' | 'portfolio' | 'debt'
  section: 'core' | 'advanced'
  unit: string
  goodValue: string
  interpretation: string
  dataSources: string[]
  traps: string[]
  interplayWith: string[]
  glossarySlug: string
  order: number
}

const PARAMETERS: ParameterDef[] = [
  {
    id: 'sameSubCategory',
    name: 'Same SEBI Sub-Category',
    category: 'pre-filter',
    section: 'core',
    unit: '—',
    goodValue: 'Must match',
    interpretation: 'Comparing funds across categories (e.g., Large Cap vs Mid Cap) is meaningless — they have different risk mandates.',
    dataSources: ['AMFI', 'SEBI classification'],
    traps: ['Never compare across sub-categories'],
    interplayWith: ['categoryFit'],
    glossarySlug: 'amfi-category',
    order: 0,
  },
  {
    id: 'samePlanType',
    name: 'Same Plan Type',
    category: 'pre-filter',
    section: 'core',
    unit: '—',
    goodValue: 'Direct vs Direct, Regular vs Regular',
    interpretation: 'Direct plans have lower expense ratios and will outperform the Regular version of the same fund.',
    dataSources: ['AMC factsheets'],
    traps: ['Always compare Direct vs Direct and Regular vs Regular separately'],
    interplayWith: ['cost'],
    glossarySlug: 'expense-ratio',
    order: 1,
  },
  {
    id: 'sufficientHistory',
    name: 'Sufficient History',
    category: 'pre-filter',
    section: 'core',
    unit: 'years',
    goodValue: '≥ 3 years for equity, ≥ 5 years for rolling returns',
    interpretation: 'Funds with less than 3 years of track record should not be compared meaningfully.',
    dataSources: ['AMC factsheets', 'Value Research'],
    traps: ['Avoid comparing funds with insufficient history — no parameter can compensate'],
    interplayWith: ['fundAge', 'consistency'],
    glossarySlug: 'nav',
    order: 2,
  },
  {
    id: 'trailingReturns',
    name: 'Trailing Returns',
    category: 'return',
    section: 'core',
    unit: '% CAGR',
    goodValue: 'Above category average and benchmark for same period',
    interpretation: 'Historical return over a specific period (1Y, 3Y, 5Y, 10Y). The most commonly quoted fund statistic.',
    dataSources: ['AMFI website', 'AMC factsheets', 'Value Research', 'Morningstar'],
    traps: [
      'Period selection bias — a fund that looks great on 3Y may be mediocre on 5Y',
      'Trailing returns hide volatility — same CAGR can have very different paths',
      'Do not extrapolate past returns into future expectations',
    ],
    interplayWith: ['consistency', 'rollingReturns'],
    glossarySlug: 'rolling-returns',
    order: 3,
  },
  {
    id: 'expenseRatio',
    name: 'Expense Ratio',
    category: 'risk',
    section: 'core',
    unit: '% p.a.',
    goodValue: 'Lower is better. Active equity Direct: 0.8–1.5%. Passive: 0.05–0.5%. Debt: 0.1–1.0%',
    interpretation: 'Annual fee charged by the AMC as a percentage of AUM. Deducted from returns before they reach you.',
    dataSources: ['SID', 'Monthly fact sheet', 'AMC website'],
    traps: [
      'A 1% higher expense ratio over 20 years can reduce final corpus by 15-20%',
      'Regular plans add ~1% vs Direct plans',
      'TER may not include exit load, STT, or brokerage',
    ],
    interplayWith: ['alpha', 'samePlanType'],
    glossarySlug: 'expense-ratio',
    order: 4,
  },
  {
    id: 'standardDeviation',
    name: 'Standard Deviation',
    category: 'risk',
    section: 'core',
    unit: '%',
    goodValue: 'Lower SD for same return is better. Equity: 12–20%. Debt: 1–5%',
    interpretation: 'Dispersion of monthly returns around the average — a measure of total risk.',
    dataSources: ['AMC factsheets', 'Value Research', 'Morningstar'],
    traps: [
      'SD penalises upside and downside volatility equally — investors care more about downside',
      'Compare SD within the same category only',
    ],
    interplayWith: ['sharpeRatio', 'sortinoRatio'],
    glossarySlug: 'nav',
    order: 5,
  },
  {
    id: 'sharpeRatio',
    name: 'Sharpe Ratio',
    category: 'risk-adjusted',
    section: 'core',
    unit: '—',
    goodValue: '> 1 is excellent, 0.5–1 is good, < 0.5 is mediocre',
    interpretation: 'Excess return per unit of total risk. Higher Sharpe means better compensation for volatility.',
    dataSources: ['AMC factsheets', 'Value Research', 'Morningstar'],
    traps: [
      'Uses total risk (SD) — downside risk (Sortino) may be more relevant for concentrated funds',
      'Different risk-free rate assumptions make Sharpe not directly comparable across sources',
    ],
    interplayWith: ['standardDeviation', 'sortinoRatio'],
    glossarySlug: 'nav',
    order: 6,
  },
  {
    id: 'alpha',
    name: 'Alpha',
    category: 'risk-adjusted',
    section: 'core',
    unit: '%',
    goodValue: 'Positive and statistically significant. > 0 means fund outperformed benchmark after risk adjustment',
    interpretation: 'Excess return relative to benchmark after adjusting for risk (beta). Measures manager skill.',
    dataSources: ['AMC factsheets', 'Value Research', 'Morningstar'],
    traps: [
      'Alpha without R-squared is unreliable — if R² < 70%, alpha may be coincidence',
      'Index funds should have alpha near zero',
      'Look at 3-5 year alpha, not just 1-year',
    ],
    interplayWith: ['rSquared', 'expenseRatio', 'beta'],
    glossarySlug: 'nav',
    order: 7,
  },
  {
    id: 'beta',
    name: 'Beta',
    category: 'risk',
    section: 'core',
    unit: '—',
    goodValue: 'Near 1.0 for large cap. Low beta (< 0.8) offers downside protection',
    interpretation: 'Sensitivity to market (benchmark) movements. Beta = 1.2 means fund moves 20% more than the market.',
    dataSources: ['AMC factsheets', 'Value Research', 'Morningstar'],
    traps: [
      'Beta is backward-looking and can change over time',
      'Low beta may simply mean low equity allocation (e.g., hybrid funds)',
      'Beta measures only market risk — not credit, liquidity, or fund-specific risk',
    ],
    interplayWith: ['alpha', 'rSquared'],
    glossarySlug: 'nav',
    order: 8,
  },
  {
    id: 'rSquared',
    name: 'R-Squared',
    category: 'risk',
    section: 'core',
    unit: '%',
    goodValue: '> 80% means alpha is meaningful. < 70% means fund differs significantly from benchmark',
    interpretation: 'Percentage of fund movements explained by benchmark index movements.',
    dataSources: ['AMC factsheets', 'Value Research', 'Morningstar'],
    traps: [
      'Low R² does not mean the fund is bad — it may have a different mandate',
      'Always check R² before interpreting alpha',
    ],
    interplayWith: ['alpha', 'beta'],
    glossarySlug: 'nav',
    order: 9,
  },
  {
    id: 'rollingReturns',
    name: 'Rolling Returns',
    category: 'return',
    section: 'core',
    unit: '% CAGR',
    goodValue: 'High average, narrow range (consistency), high % of periods beating benchmark',
    interpretation: 'Returns over consecutive overlapping periods — reveals return consistency, not just a single-point number.',
    dataSources: ['Value Research', 'Morningstar', 'Some AMC factsheets'],
    traps: [
      'Single-point trailing returns can be misleading',
      'Rolling returns reveal consistency — the single most underrated metric',
      'Minimum 5 years of data recommended for meaningful 3-year rolling return analysis',
    ],
    interplayWith: ['trailingReturns', 'consistency'],
    glossarySlug: 'rolling-returns',
    order: 10,
  },
  {
    id: 'maxDrawdown',
    name: 'Maximum Drawdown',
    category: 'risk',
    section: 'core',
    unit: '%',
    goodValue: 'Smaller (less negative) is better. Large cap: -30% to -50% in bear markets. Debt: -2% to -10%',
    interpretation: 'Largest peak-to-trough decline in NAV over a specified period.',
    dataSources: ['AMC factsheets', 'Value Research', 'Morningstar'],
    traps: [
      'MDD does not tell you recovery period',
      'Lower MDD may mean more conservative approach — check upside participation',
      'Look at MDD over a full market cycle',
    ],
    interplayWith: ['volatility'],
    glossarySlug: 'nav',
    order: 11,
  },
  {
    id: 'aum',
    name: 'AUM (Assets Under Management)',
    category: 'portfolio',
    section: 'core',
    unit: '₹ Cr',
    goodValue: 'Context-dependent. Very large (> ₹20,000Cr) may constrain mid/small cap. Very small (< ₹100Cr) risks closure',
    interpretation: 'Total market value of assets managed by the fund.',
    dataSources: ['AMC factsheets', 'AMFI data', 'Value Research'],
    traps: [
      'Large AUM can constrain mid/small cap strategies',
      'Very small AUM may lead to fund mergers or closures',
      'AUM growth through performance is good; through inflows may dilute returns',
    ],
    interplayWith: ['portfolioTurnover'],
    glossarySlug: 'aum',
    order: 12,
  },
  {
    id: 'informationRatio',
    name: 'Information Ratio',
    category: 'risk-adjusted',
    section: 'advanced',
    unit: '—',
    goodValue: '> 0.5 is good, > 1.0 is excellent',
    interpretation: 'Risk-adjusted excess return relative to benchmark, using tracking error as risk measure.',
    dataSources: ['Value Research', 'Morningstar', 'Some AMC factsheets'],
    traps: [
      'IR can be high for a fund that consistently underperforms — check the sign',
      'Low tracking error makes IR volatile',
      'Most meaningful for active funds with a clear benchmark',
    ],
    interplayWith: ['alpha', 'consistency'],
    glossarySlug: 'nav',
    order: 13,
  },
  {
    id: 'sortinoRatio',
    name: 'Sortino Ratio',
    category: 'risk-adjusted',
    section: 'advanced',
    unit: '—',
    goodValue: 'Higher is better. More meaningful than Sharpe for funds with asymmetric return profiles',
    interpretation: 'Like Sharpe but penalises only downside volatility (negative returns).',
    dataSources: ['Value Research', 'Morningstar'],
    traps: [
      'Only meaningful with sufficient data — at least 3 years of monthly returns',
      'Funds that avoid downside naturally have high Sortino — verify upside participation',
    ],
    interplayWith: ['sharpeRatio', 'standardDeviation'],
    glossarySlug: 'nav',
    order: 14,
  },
  {
    id: 'upCapture',
    name: 'Up Capture Ratio',
    category: 'risk-adjusted',
    section: 'advanced',
    unit: '%',
    goodValue: '> 100 means fund captures more upside than the market',
    interpretation: 'How much the fund participates in rising markets.',
    dataSources: ['Morningstar', 'Value Research'],
    traps: [
      'High up capture should be paired with low down capture',
      'Up capture alone is meaningless without down capture context',
    ],
    interplayWith: ['downCapture'],
    glossarySlug: 'nav',
    order: 15,
  },
  {
    id: 'downCapture',
    name: 'Down Capture Ratio',
    category: 'risk-adjusted',
    section: 'advanced',
    unit: '%',
    goodValue: '< 100 means fund falls less than the market. Up > 100 and Down < 100 is ideal',
    interpretation: 'How much the fund falls in declining markets.',
    dataSources: ['Morningstar', 'Value Research'],
    traps: [
      'Low down capture may reflect cash-heavy or debt allocation — not necessarily good stock selection',
      'Check number of down periods for statistical significance',
    ],
    interplayWith: ['upCapture'],
    glossarySlug: 'nav',
    order: 16,
  },
  {
    id: 'yieldToMaturity',
    name: 'Yield to Maturity (YTM)',
    category: 'debt',
    section: 'advanced',
    unit: '%',
    goodValue: 'Higher YTM suggests higher income, cross-checked against credit quality',
    interpretation: 'Annualised return if fund held all debt securities to maturity, assuming no defaults.',
    dataSources: ['AMC factsheets (monthly portfolio disclosure)'],
    traps: [
      'High YTM + low credit quality = potential defaults',
      'YTM changes with interest rates',
      'YTM assumes all payments reinvested at same rate',
    ],
    interplayWith: ['creditRatingProfile'],
    glossarySlug: 'nav',
    order: 17,
  },
  {
    id: 'creditRatingProfile',
    name: 'Credit Rating Profile',
    category: 'debt',
    section: 'advanced',
    unit: '% in AAA/AA/A',
    goodValue: 'Depends on fund mandate. Corporate Bond funds require min 80% in AA+ and above',
    interpretation: 'Credit quality breakdown of the debt portfolio.',
    dataSources: ['AMC factsheets (monthly portfolio disclosure)'],
    traps: [
      'Credit rating downgrades can cause sudden NAV drops',
      'Rely on portfolio disclosure, not just scheme mandate',
    ],
    interplayWith: ['yieldToMaturity'],
    glossarySlug: 'nav',
    order: 18,
  },
  {
    id: 'modifiedDuration',
    name: 'Modified Duration',
    category: 'debt',
    section: 'advanced',
    unit: 'years',
    goodValue: 'Match duration to interest rate view and investment horizon',
    interpretation: 'Sensitivity of NAV to a 1% change in interest rates. Duration of 5 means ~5% NAV drop for 1% rate rise.',
    dataSources: ['AMC factsheets'],
    traps: [
      'Higher modified duration = higher interest rate risk',
      'Duration changes as portfolio is rebalanced',
      'Liquid and Ultra Short Duration funds have near-zero duration',
    ],
    interplayWith: ['yieldToMaturity'],
    glossarySlug: 'nav',
    order: 19,
  },
  {
    id: 'portfolioTurnover',
    name: 'Portfolio Turnover Ratio',
    category: 'portfolio',
    section: 'advanced',
    unit: '%',
    goodValue: 'Lower is generally better. Large cap: 20-50%. Mid/small cap: 50-100%+. Index funds: < 10%',
    interpretation: 'How frequently the fund buys and sells securities within a year.',
    dataSources: ['AMC factsheets (annual)'],
    traps: [
      'Very low turnover (< 10%) may mean mandate drift',
      'High turnover increases brokerage costs',
      'Tax impact on short-term gains',
    ],
    interplayWith: ['cost'],
    glossarySlug: 'expense-ratio',
    order: 20,
  },
  {
    id: 'peRatio',
    name: 'P/E Ratio',
    category: 'portfolio',
    section: 'advanced',
    unit: '—',
    goodValue: 'Context-dependent. Value funds: lower P/E. Growth funds: higher P/E if justified',
    interpretation: 'Weighted average P/E ratio of stocks in the fund portfolio.',
    dataSources: ['AMC factsheets (monthly portfolio holdings)'],
    traps: [
      'P/E can be misleading with loss-making companies',
      'Sector funds have skewed P/E — compare within sector',
    ],
    interplayWith: ['categoryFit'],
    glossarySlug: 'nav',
    order: 21,
  },
  {
    id: 'dividendYield',
    name: 'Dividend Yield',
    category: 'portfolio',
    section: 'advanced',
    unit: '%',
    goodValue: 'Higher for dividend-oriented funds, lower for growth-oriented funds',
    interpretation: 'Weighted average dividend yield of stocks in the fund portfolio.',
    dataSources: ['AMC factsheets (monthly portfolio holdings)'],
    traps: [
      'Dividend yield is a portfolio characteristic, not the fund dividend payout',
      'Higher dividend yield may indicate value-oriented stocks',
    ],
    interplayWith: ['categoryFit'],
    glossarySlug: 'nav',
    order: 22,
  },
]

export function getParameter(id: string): ParameterDef | undefined {
  return PARAMETERS.find(p => p.id === id)
}

export function getParametersByCategory(cat: ParameterDef['category']): ParameterDef[] {
  return PARAMETERS.filter(p => p.category === cat)
}

export function getCoreParameters(): ParameterDef[] {
  return PARAMETERS.filter(p => p.section === 'core')
}

export function getAdvancedParameters(): ParameterDef[] {
  return PARAMETERS.filter(p => p.section === 'advanced')
}

export const MINIMAL_VIABLE_PARAMETERS = [
  'sameSubCategory',
  'expenseRatio',
  'sharpeRatio',
  'rollingReturns',
  'standardDeviation',
  'alpha',
] as const

export { PARAMETERS }
