export { useGoals } from './hooks/useGoals'
export type { GoalFormData } from './hooks/useGoals'
export { GoalForm } from './components/GoalForm'
export { GoalCard } from './components/GoalCard'
export { SIPCalculator } from './components/SIPCalculator'
export { CategoryAllocator } from './components/CategoryAllocator'
export { useCategoryMapping } from './hooks/useCategoryMapping'
export { useDriftTracking } from './hooks/useDriftTracking'
export { DriftPill } from './components/DriftPill'
export { AllocationDrift } from './components/AllocationDrift'
